BOOTLOADER = atmel-dfu # Elite-C MCU

VPATH += keyboards/gboards/

# Disable unused features
AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
LEADER_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
STENO_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
TERMINAL_ENABLE = no
UNICODE_ENABLE = no
VELOCIKEY_ENABLE = no
VIA_ENABLE = no
WPM_ENABLE = no

# Enabled features
LTO_ENABLE = yes
SPLIT_KEYBOARD = yes
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = lite
LEADER_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

# OLED displays
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
BONGOCAT_ENABLE = no

# RGB light
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no

SRC += ../../../../users/geewiz/smart_caps.c
