#ifdef RGB_MATRIX_ENABLE
#  define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_ALPHAS_MODS
#  define RGB_MATRIX_STARTUP_HUE 85
#  define RGB_MATRIX_STARTUP_SAT 135
#  define RGB_MATRIX_STARTUP_VAL 50
#  define RGB_MATRIX_STARTUP_SPD 201

#  define ENABLE_RGB_MATRIX_SOLID_COLOR
#  define ENABLE_RGB_MATRIX_ALPHAS_MODS
#  define ENABLE_RGB_MATRIX_BREATHING
#endif

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0
#define TAPPING_TERM_PER_KEY
#define TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY
#define PERMISSIVE_HOLD
#undef HOLD_ON_OTHER_KEY_PRESS

#define ACHORDION_ENABLE // features/achordion
